### ISSUE TITLE
Ausblenden der Kontaktpersonen ermöglichen nach "Create issue"

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#10]
Ausblenden der Kontaktpersonen im Modal nachdem man auf "Create issue" geklickt hat (per CSS). Klassen hinzufügen.

**Comment by winnidat** [comment]
ist da nicht jetzt im 2ten modal <ul class="supportuser" oder so

**Comment by winnidat** [comment]
https://github.com/Wunderbyte-GmbH/moodle-local_edusupport/commit/7f77c285eaef57ea782721f27d2554c226507179
