### ISSUE TITLE
Closed issue: User who requested support answers in forum

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#11]
Mögliche Szenarien:

- Issue wird wieder geöffnet (Closed -> Open)
- Antworten nach dem Closing nicht mehr ermöglichen. User  muss auf "Reopen" klicken und kann erst dann antworten

**Comment by dasistwas** [comment]
sollen wir programmieren.

**Comment by winnidat** [comment]
please test and close
