### ISSUE TITLE
Change font size for issues

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#14]
Beim Reply: Schriftgröße ist kleiner als im normalen Forum. Roboto wird verwendet. Sollte Standardschrift vom Theme sein.

**Comment by winnidat** [comment]
weiß nicht ob wir das selbe meinen aber das kommt glaub ich vom Atto Editor
![image](https://user-images.githubusercontent.com/26013011/123334477-778a2780-d543-11eb-81bd-dc6beabd8a13.png)



Also müsste man heir Atingi css umstellen
