### ISSUE TITLE
Implement privacy api

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#3]
The privacy class is empty. It has to be fully functional.

https://github.com/Wunderbyte-GmbH/moodle-local_edusupport/tree/master/classes/privacy

**Comment by dasistwas** [comment]
https://docs.moodle.org/dev/Privacy_API

**Comment by winnidat** [comment]
rdy for testing

**Comment by dasistwas** [comment]
Tests were successful
