### ISSUE TITLE
Please when a ticket is assigned it should change automatically to ‘awaiting support action’ 

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#44]
Support tickets status ‘ongoing’: at the moment, all tickets that are being assigned to someone, automatically change the status to "ongoing", also every time you reply to a ticket the status changes to ‘ongoing’ and we have to manually choose ‘awaiting user reply’.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Version 2.6 (2023022301)
