### ISSUE TITLE
When a ticket is replied to a user it should change automatically to ‘awaiting user reply’

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#45]
We discussed before that the status ‘ongoing’ would be just for tickets where we cant find a prompt solution and we have to eventually elevate them with the tech team. The status ‘ongoing’ should only be a manual process that the support team chooses when they see the need to elevate a ticket.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Version 2.6 (2023022301)
