### ISSUE TITLE
New feature sendreminders sends a lot of reminders even before it should send reminders

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#47]
How to reproduce:

1. I activate the setting sendreminders
2. I make the time between the reminders 2 days
3. I post an issue
4. I get a lot of reminders immediatly

Solution: Do not send reminder immediatly and also send only 1 reminder, not 5 or more.

**Comment by bernhard-wunderbyte** [comment]
Fixed in Version 2.6 (2023022301)
