### ISSUE TITLE
When using local_edusupport | extralinks icon in navbar is not correct

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#5]
In the admin settings of the plugin enter at least one extrlinkg like
FAQs|https://atingi.wunderbyte.at

That results in a navbar with an extra image. 

![navbar-edusup](https://user-images.githubusercontent.com/1620975/115479159-1e9eca00-a248-11eb-81f4-ad56fc91840c.png)

**Comment by dasistwas** [comment]
@winnidat bitte noch diese Woche fixen.

**Comment by winnidat** [comment]
@dasistwas sollte passen jetzt der Link Create Issue funktioniert jetzt auch da gabs auch irgendwas
