### ISSUE TITLE
Sprache bei autom. generierten Nachrichten sollte Sprache des Anfragenden sein, nicht des Support-Users

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#6]
Screenshot zeigt das Problem:
Oder ist das englische Sprachpaket auf Deutsch?

![Screenshot_2021-04-28 partner support Adding users to a new course](https://user-images.githubusercontent.com/1620975/116369106-4a521f00-a809-11eb-843e-8527d075626e.png)

**Comment by dasistwas** [comment]
@winnidat was ist der stand hier?

**Comment by winnidat** [comment]
theoretisch hätte einen Ansatz gestashed du wolltest da noch Bescheid geben ob die das wirklich wollen. (Weil die Nachrichten dass es weitergeben wird ja find ich nicht so vom Ticketschreiber abhängen )
