### ISSUE TITLE
Problem mit Gruppen

### ISSUE THREAD

**Issue by dasistwas** [Wunderbyte-GmbH/moodle-local_edusupport#8]
Wenn es im Kurs schon eine Gruppe gibt (zum Beispiel mit cohort sync erstellte Gruppe), dann wird für den User der Teil der Gruppe ist und ein Support-Ticket erstellt keine eigene Gruppe erstellt. Es bekommen dann alle Mitglieder der Gruppe die Nachrichten aus dem Support-Forum.
Fix: Trotz Zugehörigkeit zu einer bestehenden Gruppe muss eine Gruppe für den User erstellt werden und Forenbpostings mit dieser Gruppe gemacht werden und nicht mit einer anderen Gruppe des Kurses zu der der User davor schon gehört hat.

**Comment by winnidat** [comment]
hmm komisch im Code 
            $groupname = fullname($USER) . ' (' . $USER->id . ')';
                $group = $DB->get_record('groups', array('courseid' => $forum->course, 'name' => $groupname));
                if (empty($group->id)) {
                    // create a group for this user.
                    $group = (object) array(
                        'courseid' => $forum->course,
                        'name' => $groupname,
                        'description' => '',
                        'descriptionformat' => 1,
                        'timecreated' => time(),
                        'timemodified' => time(),
                    );
                    $group->id = groups_create_group($group, false);
 Groupname schaut ziemlich unique aus                  
 Ich schau es mir später an

**Comment by winnidat** [comment]
![image](https://user-images.githubusercontent.com/26013011/116460853-d135e480-a867-11eb-9691-e88cf5b9fd94.png)
lokal kann ich auswählen
